<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'flag' => 'https://flagcdn.com/w320/af.png', 'mobile_code' => '+93', 'code' => 'AF'],
            ['name' => 'Albania', 'flag' => 'https://flagcdn.com/w320/al.png', 'mobile_code' => '+355', 'code' => 'AL'],
            ['name' => 'Algeria', 'flag' => 'https://flagcdn.com/w320/dz.png', 'mobile_code' => '+213', 'code' => 'DZ'],
            ['name' => 'Andorra', 'flag' => 'https://flagcdn.com/w320/ad.png', 'mobile_code' => '+376', 'code' => 'AD'],
            ['name' => 'Angola', 'flag' => 'https://flagcdn.com/w320/ao.png', 'mobile_code' => '+244', 'code' => 'AO'],
            ['name' => 'Antigua and Barbuda', 'flag' => 'https://flagcdn.com/w320/ag.png', 'mobile_code' => '+1-268', 'code' => 'AG'],
            ['name' => 'Argentina', 'flag' => 'https://flagcdn.com/w320/ar.png', 'mobile_code' => '+54', 'code' => 'AR'],
            ['name' => 'Armenia', 'flag' => 'https://flagcdn.com/w320/am.png', 'mobile_code' => '+374', 'code' => 'AM'],
            ['name' => 'Australia', 'flag' => 'https://flagcdn.com/w320/au.png', 'mobile_code' => '+61', 'code' => 'AU'],
            ['name' => 'Austria', 'flag' => 'https://flagcdn.com/w320/at.png', 'mobile_code' => '+43', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'flag' => 'https://flagcdn.com/w320/az.png', 'mobile_code' => '+994', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'flag' => 'https://flagcdn.com/w320/bs.png', 'mobile_code' => '+1-242', 'code' => 'BS'],
            ['name' => 'Bahrain', 'flag' => 'https://flagcdn.com/w320/bh.png', 'mobile_code' => '+973', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'flag' => 'https://flagcdn.com/w320/bd.png', 'mobile_code' => '+880', 'code' => 'BD'],
            ['name' => 'Barbados', 'flag' => 'https://flagcdn.com/w320/bb.png', 'mobile_code' => '+1-246', 'code' => 'BB'],
            ['name' => 'Belarus', 'flag' => 'https://flagcdn.com/w320/by.png', 'mobile_code' => '+375', 'code' => 'BY'],
            ['name' => 'Belgium', 'flag' => 'https://flagcdn.com/w320/be.png', 'mobile_code' => '+32', 'code' => 'BE'],
            ['name' => 'Belize', 'flag' => 'https://flagcdn.com/w320/bz.png', 'mobile_code' => '+501', 'code' => 'BZ'],
            ['name' => 'Benin', 'flag' => 'https://flagcdn.com/w320/bj.png', 'mobile_code' => '+229', 'code' => 'BJ'],
            ['name' => 'Bhutan', 'flag' => 'https://flagcdn.com/w320/bt.png', 'mobile_code' => '+975', 'code' => 'BT'],
            ['name' => 'Bolivia', 'flag' => 'https://flagcdn.com/w320/bo.png', 'mobile_code' => '+591', 'code' => 'BO'],
            ['name' => 'Bosnia and Herzegovina', 'flag' => 'https://flagcdn.com/w320/ba.png', 'mobile_code' => '+387', 'code' => 'BA'],
            ['name' => 'Botswana', 'flag' => 'https://flagcdn.com/w320/bw.png', 'mobile_code' => '+267', 'code' => 'BW'],
            ['name' => 'Brazil', 'flag' => 'https://flagcdn.com/w320/br.png', 'mobile_code' => '+55', 'code' => 'BR'],
            ['name' => 'Brunei', 'flag' => 'https://flagcdn.com/w320/bn.png', 'mobile_code' => '+673', 'code' => 'BN'],
            ['name' => 'Bulgaria', 'flag' => 'https://flagcdn.com/w320/bg.png', 'mobile_code' => '+359', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'flag' => 'https://flagcdn.com/w320/bf.png', 'mobile_code' => '+226', 'code' => 'BF'],
            ['name' => 'Burundi', 'flag' => 'https://flagcdn.com/w320/bi.png', 'mobile_code' => '+257', 'code' => 'BI'],
            ['name' => 'Cabo Verde', 'flag' => 'https://flagcdn.com/w320/cv.png', 'mobile_code' => '+238', 'code' => 'CV'],
            ['name' => 'Cambodia', 'flag' => 'https://flagcdn.com/w320/kh.png', 'mobile_code' => '+855', 'code' => 'KH'],
            ['name' => 'Cameroon', 'flag' => 'https://flagcdn.com/w320/cm.png', 'mobile_code' => '+237', 'code' => 'CM'],
            ['name' => 'Canada', 'flag' => 'https://flagcdn.com/w320/ca.png', 'mobile_code' => '+1', 'code' => 'CA'],
            ['name' => 'Central African Republic', 'flag' => 'https://flagcdn.com/w320/cf.png', 'mobile_code' => '+236', 'code' => 'CF'],
            ['name' => 'Chad', 'flag' => 'https://flagcdn.com/w320/td.png', 'mobile_code' => '+235', 'code' => 'TD'],
            ['name' => 'Chile', 'flag' => 'https://flagcdn.com/w320/cl.png', 'mobile_code' => '+56', 'code' => 'CL'],
            ['name' => 'China', 'flag' => 'https://flagcdn.com/w320/cn.png', 'mobile_code' => '+86', 'code' => 'CN'],
            ['name' => 'Colombia', 'flag' => 'https://flagcdn.com/w320/co.png', 'mobile_code' => '+57', 'code' => 'CO'],
            ['name' => 'Comoros', 'flag' => 'https://flagcdn.com/w320/km.png', 'mobile_code' => '+269', 'code' => 'KM'],
            ['name' => 'Congo (Congo-Brazzaville)', 'flag' => 'https://flagcdn.com/w320/cg.png', 'mobile_code' => '+242', 'code' => 'CG'],
            ['name' => 'Costa Rica', 'flag' => 'https://flagcdn.com/w320/cr.png', 'mobile_code' => '+506', 'code' => 'CR'],
            ['name' => 'Croatia', 'flag' => 'https://flagcdn.com/w320/hr.png', 'mobile_code' => '+385', 'code' => 'HR'],
            ['name' => 'Cuba', 'flag' => 'https://flagcdn.com/w320/cu.png', 'mobile_code' => '+53', 'code' => 'CU'],
            ['name' => 'Cyprus', 'flag' => 'https://flagcdn.com/w320/cy.png', 'mobile_code' => '+357', 'code' => 'CY'],
            ['name' => 'Czechia (Czech Republic)', 'flag' => 'https://flagcdn.com/w320/cz.png', 'mobile_code' => '+420', 'code' => 'CZ'],
            ['name' => 'Denmark', 'flag' => 'https://flagcdn.com/w320/dk.png', 'mobile_code' => '+45', 'code' => 'DK'],
            ['name' => 'Djibouti', 'flag' => 'https://flagcdn.com/w320/dj.png', 'mobile_code' => '+253', 'code' => 'DJ'],
            ['name' => 'Dominica', 'flag' => 'https://flagcdn.com/w320/dm.png', 'mobile_code' => '+1-767', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'flag' => 'https://flagcdn.com/w320/do.png', 'mobile_code' => '+1-809', 'code' => 'DO'],
            ['name' => 'Egypt', 'flag' => 'https://flagcdn.com/w320/eg.png', 'mobile_code' => '+20', 'code' => 'EG'],
            ['name' => 'El Salvador', 'flag' => 'https://flagcdn.com/w320/sv.png', 'mobile_code' => '+503', 'code' => 'SV'],
            ['name' => 'Equatorial Guinea', 'flag' => 'https://flagcdn.com/w320/gq.png', 'mobile_code' => '+240', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'flag' => 'https://flagcdn.com/w320/er.png', 'mobile_code' => '+291', 'code' => 'ER'],
            ['name' => 'Estonia', 'flag' => 'https://flagcdn.com/w320/ee.png', 'mobile_code' => '+372', 'code' => 'EE'],
            ['name' => 'Eswatini (fmr. "Swaziland")', 'flag' => 'https://flagcdn.com/w320/sz.png', 'mobile_code' => '+268', 'code' => 'SZ'],
            ['name' => 'Ethiopia', 'flag' => 'https://flagcdn.com/w320/et.png', 'mobile_code' => '+251', 'code' => 'ET'],
            ['name' => 'Fiji', 'flag' => 'https://flagcdn.com/w320/fj.png', 'mobile_code' => '+679', 'code' => 'FJ'],
            ['name' => 'Finland', 'flag' => 'https://flagcdn.com/w320/fi.png', 'mobile_code' => '+358', 'code' => 'FI'],
            ['name' => 'France', 'flag' => 'https://flagcdn.com/w320/fr.png', 'mobile_code' => '+33', 'code' => 'FR'],
            ['name' => 'Gabon', 'flag' => 'https://flagcdn.com/w320/ga.png', 'mobile_code' => '+241', 'code' => 'GA'],
            ['name' => 'Gambia', 'flag' => 'https://flagcdn.com/w320/gm.png', 'mobile_code' => '+220', 'code' => 'GM'],
            ['name' => 'Georgia', 'flag' => 'https://flagcdn.com/w320/ge.png', 'mobile_code' => '+995', 'code' => 'GE'],
            ['name' => 'Germany', 'flag' => 'https://flagcdn.com/w320/de.png', 'mobile_code' => '+49', 'code' => 'DE'],
            ['name' => 'Ghana', 'flag' => 'https://flagcdn.com/w320/gh.png', 'mobile_code' => '+233', 'code' => 'GH'],
            ['name' => 'Greece', 'flag' => 'https://flagcdn.com/w320/gr.png', 'mobile_code' => '+30', 'code' => 'GR'],
            ['name' => 'Grenada', 'flag' => 'https://flagcdn.com/w320/gd.png', 'mobile_code' => '+1-473', 'code' => 'GD'],
            ['name' => 'Guatemala', 'flag' => 'https://flagcdn.com/w320/gt.png', 'mobile_code' => '+502', 'code' => 'GT'],
            ['name' => 'Guinea', 'flag' => 'https://flagcdn.com/w320/gn.png', 'mobile_code' => '+224', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'flag' => 'https://flagcdn.com/w320/gw.png', 'mobile_code' => '+245', 'code' => 'GW'],
            ['name' => 'Guyana', 'flag' => 'https://flagcdn.com/w320/gy.png', 'mobile_code' => '+592', 'code' => 'GY'],
            ['name' => 'Haiti', 'flag' => 'https://flagcdn.com/w320/ht.png', 'mobile_code' => '+509', 'code' => 'HT'],
            ['name' => 'Honduras', 'flag' => 'https://flagcdn.com/w320/hn.png', 'mobile_code' => '+504', 'code' => 'HN'],
            ['name' => 'Hungary', 'flag' => 'https://flagcdn.com/w320/hu.png', 'mobile_code' => '+36', 'code' => 'HU'],
            ['name' => 'Iceland', 'flag' => 'https://flagcdn.com/w320/is.png', 'mobile_code' => '+354', 'code' => 'IS'],
            ['name' => 'India', 'flag' => 'https://flagcdn.com/w320/in.png', 'mobile_code' => '+91', 'code' => 'IN'],
            ['name' => 'Indonesia', 'flag' => 'https://flagcdn.com/w320/id.png', 'mobile_code' => '+62', 'code' => 'ID'],
            ['name' => 'Iran', 'flag' => 'https://flagcdn.com/w320/ir.png', 'mobile_code' => '+98', 'code' => 'IR'],
            ['name' => 'Iraq', 'flag' => 'https://flagcdn.com/w320/iq.png', 'mobile_code' => '+964', 'code' => 'IQ'],
            ['name' => 'Ireland', 'flag' => 'https://flagcdn.com/w320/ie.png', 'mobile_code' => '+353', 'code' => 'IE'],
            ['name' => 'Israel', 'flag' => 'https://flagcdn.com/w320/il.png', 'mobile_code' => '+972', 'code' => 'IL'],
            ['name' => 'Italy', 'flag' => 'https://flagcdn.com/w320/it.png', 'mobile_code' => '+39', 'code' => 'IT'],
            ['name' => 'Jamaica', 'flag' => 'https://flagcdn.com/w320/jm.png', 'mobile_code' => '+1-876', 'code' => 'JM'],
            ['name' => 'Japan', 'flag' => 'https://flagcdn.com/w320/jp.png', 'mobile_code' => '+81', 'code' => 'JP'],
            ['name' => 'Jordan', 'flag' => 'https://flagcdn.com/w320/jo.png', 'mobile_code' => '+962', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'flag' => 'https://flagcdn.com/w320/kz.png', 'mobile_code' => '+7', 'code' => 'KZ'],
            ['name' => 'Kenya', 'flag' => 'https://flagcdn.com/w320/ke.png', 'mobile_code' => '+254', 'code' => 'KE'],
            ['name' => 'Kiribati', 'flag' => 'https://flagcdn.com/w320/ki.png', 'mobile_code' => '+686', 'code' => 'KI'],
            ['name' => 'Korea, North', 'flag' => 'https://flagcdn.com/w320/kp.png', 'mobile_code' => '+850', 'code' => 'KP'],
            ['name' => 'Korea, South', 'flag' => 'https://flagcdn.com/w320/kr.png', 'mobile_code' => '+82', 'code' => 'KR'],
            ['name' => 'Kosovo', 'flag' => 'https://flagcdn.com/w320/xk.png', 'mobile_code' => '+383', 'code' => 'XK'],
            ['name' => 'Kuwait', 'flag' => 'https://flagcdn.com/w320/kw.png', 'mobile_code' => '+965', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'flag' => 'https://flagcdn.com/w320/kg.png', 'mobile_code' => '+996', 'code' => 'KG'],
            ['name' => 'Laos', 'flag' => 'https://flagcdn.com/w320/la.png', 'mobile_code' => '+856', 'code' => 'LA'],
            ['name' => 'Latvia', 'flag' => 'https://flagcdn.com/w320/lv.png', 'mobile_code' => '+371', 'code' => 'LV'],
            ['name' => 'Lebanon', 'flag' => 'https://flagcdn.com/w320/lb.png', 'mobile_code' => '+961', 'code' => 'LB'],
            ['name' => 'Lesotho', 'flag' => 'https://flagcdn.com/w320/ls.png', 'mobile_code' => '+266', 'code' => 'LS'],
            ['name' => 'Liberia', 'flag' => 'https://flagcdn.com/w320/lr.png', 'mobile_code' => '+231', 'code' => 'LR'],
            ['name' => 'Libya', 'flag' => 'https://flagcdn.com/w320/ly.png', 'mobile_code' => '+218', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'flag' => 'https://flagcdn.com/w320/li.png', 'mobile_code' => '+423', 'code' => 'LI'],
            ['name' => 'Lithuania', 'flag' => 'https://flagcdn.com/w320/lt.png', 'mobile_code' => '+370', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'flag' => 'https://flagcdn.com/w320/lu.png', 'mobile_code' => '+352', 'code' => 'LU'],
            ['name' => 'Madagascar', 'flag' => 'https://flagcdn.com/w320/mg.png', 'mobile_code' => '+261', 'code' => 'MG'],
            ['name' => 'Malawi', 'flag' => 'https://flagcdn.com/w320/mw.png', 'mobile_code' => '+265', 'code' => 'MW'],
            ['name' => 'Malaysia', 'flag' => 'https://flagcdn.com/w320/my.png', 'mobile_code' => '+60', 'code' => 'MY'],
            ['name' => 'Maldives', 'flag' => 'https://flagcdn.com/w320/mv.png', 'mobile_code' => '+960', 'code' => 'MV'],
            ['name' => 'Mali', 'flag' => 'https://flagcdn.com/w320/ml.png', 'mobile_code' => '+223', 'code' => 'ML'],
            ['name' => 'Malta', 'flag' => 'https://flagcdn.com/w320/mt.png', 'mobile_code' => '+356', 'code' => 'MT'],
            ['name' => 'Marshall Islands', 'flag' => 'https://flagcdn.com/w320/mh.png', 'mobile_code' => '+692', 'code' => 'MH'],
            ['name' => 'Mauritania', 'flag' => 'https://flagcdn.com/w320/mr.png', 'mobile_code' => '+222', 'code' => 'MR'],
            ['name' => 'Mauritius', 'flag' => 'https://flagcdn.com/w320/mu.png', 'mobile_code' => '+230', 'code' => 'MU'],
            ['name' => 'Mexico', 'flag' => 'https://flagcdn.com/w320/mx.png', 'mobile_code' => '+52', 'code' => 'MX'],
            ['name' => 'Micronesia', 'flag' => 'https://flagcdn.com/w320/fm.png', 'mobile_code' => '+691', 'code' => 'FM'],
            ['name' => 'Moldova', 'flag' => 'https://flagcdn.com/w320/md.png', 'mobile_code' => '+373', 'code' => 'MD'],
            ['name' => 'Monaco', 'flag' => 'https://flagcdn.com/w320/mc.png', 'mobile_code' => '+377', 'code' => 'MC'],
            ['name' => 'Mongolia', 'flag' => 'https://flagcdn.com/w320/mn.png', 'mobile_code' => '+976', 'code' => 'MN'],
            ['name' => 'Montenegro', 'flag' => 'https://flagcdn.com/w320/me.png', 'mobile_code' => '+382', 'code' => 'ME'],
            ['name' => 'Morocco', 'flag' => 'https://flagcdn.com/w320/ma.png', 'mobile_code' => '+212', 'code' => 'MA'],
            ['name' => 'Mozambique', 'flag' => 'https://flagcdn.com/w320/mz.png', 'mobile_code' => '+258', 'code' => 'MZ'],
            ['name' => 'Myanmar (Burma)', 'flag' => 'https://flagcdn.com/w320/mm.png', 'mobile_code' => '+95', 'code' => 'MM'],
            ['name' => 'Namibia', 'flag' => 'https://flagcdn.com/w320/na.png', 'mobile_code' => '+264', 'code' => 'NA'],
            ['name' => 'Nauru', 'flag' => 'https://flagcdn.com/w320/nr.png', 'mobile_code' => '+674', 'code' => 'NR'],
            ['name' => 'Nepal', 'flag' => 'https://flagcdn.com/w320/np.png', 'mobile_code' => '+977', 'code' => 'NP'],
            ['name' => 'Netherlands', 'flag' => 'https://flagcdn.com/w320/nl.png', 'mobile_code' => '+31', 'code' => 'NL'],
            ['name' => 'New Zealand', 'flag' => 'https://flagcdn.com/w320/nz.png', 'mobile_code' => '+64', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'flag' => 'https://flagcdn.com/w320/ni.png', 'mobile_code' => '+505', 'code' => 'NI'],
            ['name' => 'Niger', 'flag' => 'https://flagcdn.com/w320/ne.png', 'mobile_code' => '+227', 'code' => 'NE'],
            ['name' => 'Nigeria', 'flag' => 'https://flagcdn.com/w320/ng.png', 'mobile_code' => '+234', 'code' => 'NG'],
            ['name' => 'North Macedonia', 'flag' => 'https://flagcdn.com/w320/mk.png', 'mobile_code' => '+389', 'code' => 'MK'],
            ['name' => 'Norway', 'flag' => 'https://flagcdn.com/w320/no.png', 'mobile_code' => '+47', 'code' => 'NO'],
            ['name' => 'Oman', 'flag' => 'https://flagcdn.com/w320/om.png', 'mobile_code' => '+968', 'code' => 'OM'],
            ['name' => 'Pakistan', 'flag' => 'https://flagcdn.com/w320/pk.png', 'mobile_code' => '+92', 'code' => 'PK'],
            ['name' => 'Palau', 'flag' => 'https://flagcdn.com/w320/pw.png', 'mobile_code' => '+680', 'code' => 'PW'],
            ['name' => 'Panama', 'flag' => 'https://flagcdn.com/w320/pa.png', 'mobile_code' => '+507', 'code' => 'PA'],
            ['name' => 'Papua New Guinea', 'flag' => 'https://flagcdn.com/w320/pg.png', 'mobile_code' => '+675', 'code' => 'PG'],
            ['name' => 'Paraguay', 'flag' => 'https://flagcdn.com/w320/py.png', 'mobile_code' => '+595', 'code' => 'PY'],
            ['name' => 'Peru', 'flag' => 'https://flagcdn.com/w320/pe.png', 'mobile_code' => '+51', 'code' => 'PE'],
            ['name' => 'Philippines', 'flag' => 'https://flagcdn.com/w320/ph.png', 'mobile_code' => '+63', 'code' => 'PH'],
            ['name' => 'Poland', 'flag' => 'https://flagcdn.com/w320/pl.png', 'mobile_code' => '+48', 'code' => 'PL'],
            ['name' => 'Portugal', 'flag' => 'https://flagcdn.com/w320/pt.png', 'mobile_code' => '+351', 'code' => 'PT'],
            ['name' => 'Qatar', 'flag' => 'https://flagcdn.com/w320/qa.png', 'mobile_code' => '+974', 'code' => 'QA'],
            ['name' => 'Romania', 'flag' => 'https://flagcdn.com/w320/ro.png', 'mobile_code' => '+40', 'code' => 'RO'],
            ['name' => 'Russia', 'flag' => 'https://flagcdn.com/w320/ru.png', 'mobile_code' => '+7', 'code' => 'RU'],
            ['name' => 'Rwanda', 'flag' => 'https://flagcdn.com/w320/rw.png', 'mobile_code' => '+250', 'code' => 'RW'],
            ['name' => 'Saint Kitts and Nevis', 'flag' => 'https://flagcdn.com/w320/kn.png', 'mobile_code' => '+1-869', 'code' => 'KN'],
            ['name' => 'Saint Lucia', 'flag' => 'https://flagcdn.com/w320/lc.png', 'mobile_code' => '+1-758', 'code' => 'LC'],
            ['name' => 'Saint Vincent and the Grenadines', 'flag' => 'https://flagcdn.com/w320/vc.png', 'mobile_code' => '+1-784', 'code' => 'VC'],
            ['name' => 'Samoa', 'flag' => 'https://flagcdn.com/w320/ws.png', 'mobile_code' => '+685', 'code' => 'WS'],
            ['name' => 'San Marino', 'flag' => 'https://flagcdn.com/w320/sm.png', 'mobile_code' => '+378', 'code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'flag' => 'https://flagcdn.com/w320/st.png', 'mobile_code' => '+239', 'code' => 'ST'],
            ['name' => 'Saudi Arabia', 'flag' => 'https://flagcdn.com/w320/sa.png', 'mobile_code' => '+966', 'code' => 'SA'],
            ['name' => 'Senegal', 'flag' => 'https://flagcdn.com/w320/sn.png', 'mobile_code' => '+221', 'code' => 'SN'],
            ['name' => 'Serbia', 'flag' => 'https://flagcdn.com/w320/rs.png', 'mobile_code' => '+381', 'code' => 'RS'],
            ['name' => 'Seychelles', 'flag' => 'https://flagcdn.com/w320/sc.png', 'mobile_code' => '+248', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'flag' => 'https://flagcdn.com/w320/sl.png', 'mobile_code' => '+232', 'code' => 'SL'],
            ['name' => 'Singapore', 'flag' => 'https://flagcdn.com/w320/sg.png', 'mobile_code' => '+65', 'code' => 'SG'],
            ['name' => 'Slovakia', 'flag' => 'https://flagcdn.com/w320/sk.png', 'mobile_code' => '+421', 'code' => 'SK'],
            ['name' => 'Slovenia', 'flag' => 'https://flagcdn.com/w320/si.png', 'mobile_code' => '+386', 'code' => 'SI'],
            ['name' => 'Solomon Islands', 'flag' => 'https://flagcdn.com/w320/sb.png', 'mobile_code' => '+677', 'code' => 'SB'],
            ['name' => 'Somalia', 'flag' => 'https://flagcdn.com/w320/so.png', 'mobile_code' => '+252', 'code' => 'SO'],
            ['name' => 'South Africa', 'flag' => 'https://flagcdn.com/w320/za.png', 'mobile_code' => '+27', 'code' => 'ZA'],
            ['name' => 'South Sudan', 'flag' => 'https://flagcdn.com/w320/ss.png', 'mobile_code' => '+211', 'code' => 'SS'],
            ['name' => 'Spain', 'flag' => 'https://flagcdn.com/w320/es.png', 'mobile_code' => '+34', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'flag' => 'https://flagcdn.com/w320/lk.png', 'mobile_code' => '+94', 'code' => 'LK'],
            ['name' => 'Sudan', 'flag' => 'https://flagcdn.com/w320/sd.png', 'mobile_code' => '+249', 'code' => 'SD'],
            ['name' => 'Suriname', 'flag' => 'https://flagcdn.com/w320/sr.png', 'mobile_code' => '+597', 'code' => 'SR'],
            ['name' => 'Sweden', 'flag' => 'https://flagcdn.com/w320/se.png', 'mobile_code' => '+46', 'code' => 'SE'],
            ['name' => 'Switzerland', 'flag' => 'https://flagcdn.com/w320/ch.png', 'mobile_code' => '+41', 'code' => 'CH'],
            ['name' => 'Syria', 'flag' => 'https://flagcdn.com/w320/sy.png', 'mobile_code' => '+963', 'code' => 'SY'],
            ['name' => 'Taiwan', 'flag' => 'https://flagcdn.com/w320/tw.png', 'mobile_code' => '+886', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'flag' => 'https://flagcdn.com/w320/tj.png', 'mobile_code' => '+992', 'code' => 'TJ'],
            ['name' => 'Tanzania', 'flag' => 'https://flagcdn.com/w320/tz.png', 'mobile_code' => '+255', 'code' => 'TZ'],
            ['name' => 'Thailand', 'flag' => 'https://flagcdn.com/w320/th.png', 'mobile_code' => '+66', 'code' => 'TH'],
            ['name' => 'Timor-Leste', 'flag' => 'https://flagcdn.com/w320/tl.png', 'mobile_code' => '+670', 'code' => 'TL'],
            ['name' => 'Togo', 'flag' => 'https://flagcdn.com/w320/tg.png', 'mobile_code' => '+228', 'code' => 'TG'],
            ['name' => 'Tonga', 'flag' => 'https://flagcdn.com/w320/to.png', 'mobile_code' => '+676', 'code' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'flag' => 'https://flagcdn.com/w320/tt.png', 'mobile_code' => '+1-868', 'code' => 'TT'],
            ['name' => 'Tunisia', 'flag' => 'https://flagcdn.com/w320/tn.png', 'mobile_code' => '+216', 'code' => 'TN'],
            ['name' => 'Turkey', 'flag' => 'https://flagcdn.com/w320/tr.png', 'mobile_code' => '+90', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'flag' => 'https://flagcdn.com/w320/tm.png', 'mobile_code' => '+993', 'code' => 'TM'],
            ['name' => 'Tuvalu', 'flag' => 'https://flagcdn.com/w320/tv.png', 'mobile_code' => '+688', 'code' => 'TV'],
            ['name' => 'Uganda', 'flag' => 'https://flagcdn.com/w320/ug.png', 'mobile_code' => '+256', 'code' => 'UG'],
            ['name' => 'Ukraine', 'flag' => 'https://flagcdn.com/w320/ua.png', 'mobile_code' => '+380', 'code' => 'UA'],
            ['name' => 'United Arab Emirates', 'flag' => 'https://flagcdn.com/w320/ae.png', 'mobile_code' => '+971', 'code' => 'AE'],
            ['name' => 'United Kingdom', 'flag' => 'https://flagcdn.com/w320/gb.png', 'mobile_code' => '+44', 'code' => 'GB'],
            ['name' => 'United States', 'flag' => 'https://flagcdn.com/w320/us.png', 'mobile_code' => '+1', 'code' => 'US'],
            ['name' => 'Uruguay', 'flag' => 'https://flagcdn.com/w320/uy.png', 'mobile_code' => '+598', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'flag' => 'https://flagcdn.com/w320/uz.png', 'mobile_code' => '+998', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'flag' => 'https://flagcdn.com/w320/vu.png', 'mobile_code' => '+678', 'code' => 'VU'],
            ['name' => 'Vatican City', 'flag' => 'https://flagcdn.com/w320/va.png', 'mobile_code' => '+379', 'code' => 'VA'],
            ['name' => 'Venezuela', 'flag' => 'https://flagcdn.com/w320/ve.png', 'mobile_code' => '+58', 'code' => 'VE'],
            ['name' => 'Vietnam', 'flag' => 'https://flagcdn.com/w320/vn.png', 'mobile_code' => '+84', 'code' => 'VN'],
            ['name' => 'Yemen', 'flag' => 'https://flagcdn.com/w320/ye.png', 'mobile_code' => '+967', 'code' => 'YE'],
            ['name' => 'Zambia', 'flag' => 'https://flagcdn.com/w320/zm.png', 'mobile_code' => '+260', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'flag' => 'https://flagcdn.com/w320/zw.png', 'mobile_code' => '+263', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            Country::create([
                'name' => $country['name'],
                'flag' => $country['flag'],
                'mobile_code' => $country['mobile_code'],
                'code' => $country['code'],
            ]);
        }
    }
}